#!/bin/bash
# Test: Apache-compatible htpasswd hash formats
#   {SHA}<b64>      - base64(SHA-1(plain))
#   $apr1$<salt>$.. - Apache APR1 MD5

# Both files are generated by run_tests.sh / Dockerfile with password
# "testpass" for user "shauser" (sha) and "aprser" (apr1).

# --- {SHA} ---
begin_test "{SHA} - correct credentials -> 200"
status=$(curl -s -o /dev/null -w "%{http_code}" \
    -u "shauser:testpass" "${BASE_URL}/auth-sha/page.html")
[ "$status" = "200" ] && pass || fail "expected 200, got $status"

begin_test "{SHA} - wrong password -> 401"
assert_status_with_header GET /auth-sha/page.html 401 \
    "Authorization: Basic $(echo -n 'shauser:WRONG' | base64)"

begin_test "{SHA} - no credentials -> 401"
assert_status GET /auth-sha/page.html 401

# --- $apr1$ ---
begin_test "\$apr1\$ - correct credentials -> 200"
status=$(curl -s -o /dev/null -w "%{http_code}" \
    -u "apruser:testpass" "${BASE_URL}/auth-apr1/page.html")
[ "$status" = "200" ] && pass || fail "expected 200, got $status"

begin_test "\$apr1\$ - wrong password -> 401"
assert_status_with_header GET /auth-apr1/page.html 401 \
    "Authorization: Basic $(echo -n 'apruser:WRONG' | base64)"
